name: dart_code_snippets
description: A library for collecting Dart code examples, such as testing feature codes or some helper codes.
# version: 0.0.1
# homepage: https://github.com/binderclip/code-snippets-dart
# author: clip <binderclip2014#gmail.com>

environment:
  sdk: ^2.0.0

dependencies:
  meta: ^1.1.6
  english_words: ^3.1.3
  uuid: ^1.0.0
  quiver: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
